---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: cilium
spec:
  url: https://helm.cilium.io/
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: ">=1.16.0"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: cilium
      interval: 12h
  values:
    # Cilium configuration
    cluster:
      name: "k8s-cluster"
      id: 1

    # Talos-specific configuration
    # Use Kubernetes IPAM mode as Talos assigns PodCIDRs to v1.Node resources
    ipam:
      mode: kubernetes

    # Kube-proxy replacement configuration
    kubeProxyReplacement: true
    k8sServiceHost: localhost
    k8sServicePort: 7445

    # Talos security context - drop SYS_MODULE capability
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE

    # Talos cgroup configuration - reuse cgroupv2 mount
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup

    # Enable host legacy routing for DNS compatibility with Talos
    bpf:
      hostLegacyRouting: true

    # Enable Hubble for observability
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true

    # Enable CNI and replace kube-proxy
    cni:
      exclusive: true

    # Enable Gateway API support
    gatewayAPI:
      enabled: true

    # Enable L7 proxy for application-level policies
    l7Proxy: true

    # Resource management
    operator:
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 128Mi

    # Agent resources
    resources:
      limits:
        cpu: 4000m
        memory: 4Gi
      requests:
        cpu: 100m
        memory: 512Mi
