---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudflare
  namespace: cloudflare-tunnel
spec:
  url: https://cloudflare.github.io/helm-charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: "0.3.2"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: cloudflare-tunnel
  values:
    cloudflare:
      secretName: cloudflare-tunnel-token
      tunnelName: k8s
      tunnelId: 31e83007-176a-4a06-8363-e99d39271e55
    replicaCount: 2
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - cloudflare-tunnel
            topologyKey: "kubernetes.io/hostname"
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65532
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
