---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudflare
  namespace: cloudflare-tunnel
spec:
  url: https://cloudflare.github.io/helm-charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudflare-tunnel
      version: "0.3.2"
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: cloudflare-tunnel
  values:
    cloudflare:
      secretName: cloudflare-tunnel-token
      tunnel: k8s
      ingress:
        # Route demo.mkskytt.dev to the nginx demo service
        - hostname: demo.mkskytt.dev
          service: http://nginx-demo.demo-app.svc.cluster.local:80
    replicaCount: 2
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65532
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
