apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudflared
  namespace: cloudflare-tunnel
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflare-tunnel
