---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  url: https://cloudflare.github.io/helm-charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 5m
  chart:
    spec:
      chart: cloudflared
      version: 0.3.0
      sourceRef:
        kind: HelmRepository
        name: cloudflared
        namespace: cloudflared
  values:
    # Cloudflare tunnel configuration
    cloudflare:
      tunnel_token:
        existingSecret: cloudflare-tunnel-token
        key: tunnel-token

    # Tunnel routing configuration - direct to services
    tunnel:
      ingress:
        - hostname: "app.k8s.mkskytt.dev"
          service: "http://my-app-service.default.svc.cluster.local:80"
        - hostname: "api.k8s.mkskytt.dev"
          service: "http://my-api-service.default.svc.cluster.local:8080"
        - hostname: "dashboard.k8s.mkskytt.dev"
          service: "http://dashboard-service.default.svc.cluster.local:3000"
        - hostname: "hubble.k8s.mkskytt.dev"
          service: "http://hubble-ui.kube-system.svc.cluster.local:80"
        # Catch-all rule (required by cloudflared)
        - service: "http_status:404"

    # Deployment configuration
    replicaCount: 2

    # Resource limits
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

    # Pod security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      readOnlyRootFilesystem: true

    # Node selector (optional)
    nodeSelector: {}

    # Tolerations (optional)
    tolerations: []

    # Affinity rules
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: cloudflared
              topologyKey: kubernetes.io/hostname
