---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: demo-app
  namespace: demo-app
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: "6.7.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      interval: 5m
  values:
    # Replica configuration
    replicaCount: 2

    # Image configuration
    image:
      repository: stefanprodan/podinfo
      tag: "6.7.0"
      pullPolicy: IfNotPresent

    # Service configuration
    service:
      enabled: true
      type: ClusterIP
      port: 9898
      containerPort: 9898
      protocol: TCP

    # Ingress disabled (using cloudflared tunnel)
    ingress:
      enabled: false

    # Resource limits
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 64Mi
        cpu: 100m

    # Probes
    probes:
      liveness:
        enabled: true
        path: /healthz
        initialDelaySeconds: 5
        timeoutSeconds: 5
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readiness:
        enabled: true
        path: /readyz
        initialDelaySeconds: 5
        timeoutSeconds: 5
        periodSeconds: 5
        successThreshold: 1
        failureThreshold: 3

    # UI configuration
    ui:
      color: "#34577c"
      message: "Greetings from demo-app deployed with Flux!"
      logo: "https://raw.githubusercontent.com/stefanprodan/podinfo/gh-pages/cuddle_clap.gif"

    # Horizontal Pod Autoscaler
    hpa:
      enabled: false

    # Service Monitor for Prometheus (if available)
    serviceMonitor:
      enabled: false

    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 10001
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL

    # Pod security context
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 10001
      runAsGroup: 10001
      fsGroup: 10001
