---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-app-ingress
  namespace: demo-app
  annotations:
    cloudflare-tunnel.io/hostname: "demo.mkskytt.dev"
spec:
  rules:
    - host: demo.mkskytt.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-demo
                port:
                  number: 80
