---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dapr
  namespace: dapr-system
spec:
  interval: 1h
  url: https://dapr.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dapr
  namespace: dapr-system
spec:
  interval: 5m
  chart:
    spec:
      chart: dapr
      version: 1.13.2
      sourceRef:
        kind: HelmRepository
        name: dapr
        namespace: dapr-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dapr-dashboard
  namespace: dapr-system
spec:
  interval: 5m
  chart:
    spec:
      chart: dapr-dashboard
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: dapr
        namespace: dapr-system
