---
# Direct Service Routing Configuration for Multi-Tenant CNAME Architecture
# This configuration supports cloudflared tunneling directly to services
# without an ingress controller layer

# External-DNS configuration for automatic DNS management
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-tunnel-config
  namespace: default
data:
  config.yaml: |
    # Cloudflared tunnel configuration for direct service routing
    # Configure these routes in your Cloudflare dashboard:
    #
    # app.k8s.mkskytt.dev     -> http://my-app-service.default.svc.cluster.local:80
    # api.k8s.mkskytt.dev     -> http://my-api-service.default.svc.cluster.local:8080  
    # dashboard.k8s.mkskytt.dev -> http://dashboard-service.default.svc.cluster.local:3000
    # hubble.k8s.mkskytt.dev  -> http://hubble-ui.kube-system.svc.cluster.local:80
    #
    # Customer domains (via CNAME):
    # myapp.com               -> app.k8s.mkskytt.dev (automatically routed)
    # api.myapp.com           -> api.k8s.mkskytt.dev (automatically routed)
    # dashboard.myapp.com     -> dashboard.k8s.mkskytt.dev (automatically routed)

---
# External-DNS annotation for service discovery
# This helps external-dns create DNS records for your infrastructure domains
apiVersion: v1
kind: Service
metadata:
  name: external-dns-reference
  namespace: default
  annotations:
    # These annotations help external-dns create the necessary DNS records
    external-dns.alpha.kubernetes.io/hostname: "app.k8s.mkskytt.dev,api.k8s.mkskytt.dev,dashboard.k8s.mkskytt.dev,hubble.k8s.mkskytt.dev"
spec:
  type: ExternalName
  externalName: tunnel.cloudflare.com  # Points to your cloudflared tunnel
  ports:
  - port: 80
    name: http
  - port: 443  
    name: https