---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kyverno
  namespace: kyverno
spec:
  url: https://kyverno.github.io/kyverno/
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: ">=3.3.0, <4.0.0"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      interval: 12h
  values:
    admissionController:
      enabled: true
      replicas: 1
      resources:
        limits:
          memory: 384Mi
        requests:
          cpu: 100m
          memory: 128Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 10001
        capabilities:
          drop:
            - ALL

    backgroundController:
      enabled: true
      replicas: 1
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 10001
        capabilities:
          drop:
            - ALL

    cleanupController:
      enabled: true
      replicas: 1
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 10001
        capabilities:
          drop:
            - ALL

    reportsController:
      enabled: true
      replicas: 1
      resources:
        limits:
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 64Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 10001
        capabilities:
          drop:
            - ALL

    config:
      resourceFilters:
        - "[*/*,kyverno,*]"
        - "[Event,*,*]"
        - "[*/*,kube-system,*]"
        - "[*/*,kube-public,*]"
        - "[*/*,kube-node-lease,*]"
        - "[Node,*,*]"
        - "[APIService,*,*]"
        - "[TokenReview,*,*]"
        - "[SubjectAccessReview,*,*]"
        - "[SelfSubjectAccessReview,*,*]"
        - "[Binding,*,*]"
        - "[ReplicaSet,*,*]"
        - "[ReportChangeRequest,*,*]"
        - "[ClusterReportChangeRequest,*,*]"

    features:
      admissionReports:
        enabled: true
      backgroundScan:
        enabled: true
      configMapCaching:
        enabled: true
      policyExceptions:
        enabled: true
        namespace: kyverno

    grafana:
      enabled: false
    serviceMonitor:
      enabled: false
