apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-container-registries
  annotations:
    policies.kyverno.io/title: Restrict Container Registries
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      This policy ensures that only container images from the approved Azure Container Registry
      'mkskytt.azurecr.io' are allowed to be deployed in the cluster. This helps maintain
      security by preventing the use of untrusted or unauthorized container registries.
spec:
  validationFailureAction: enforce
  background: true
  rules:
  - name: check-registry
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "Container images must be from the approved Azure Container Registry 'mkskytt.azurecr.io'. Only images with the prefix 'mkskytt.azurecr.io/' are allowed."
      pattern:
        spec:
          containers:
          - image: "mkskytt.azurecr.io/*"
  - name: check-init-containers
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      any:
      - key: "{{ request.object.spec.initContainers || `[]` | length(@) }}"
        operator: GreaterThan
        value: 0
    validate:
      message: "Init container images must be from the approved Azure Container Registry 'mkskytt.azurecr.io'. Only images with the prefix 'mkskytt.azurecr.io/' are allowed."
      pattern:
        spec:
          initContainers:
          - image: "mkskytt.azurecr.io/*"
  - name: check-ephemeral-containers
    match:
      any:
      - resources:
          kinds:
          - Pod
    preconditions:
      any:
      - key: "{{ request.object.spec.ephemeralContainers || `[]` | length(@) }}"
        operator: GreaterThan
        value: 0
    validate:
      message: "Ephemeral container images must be from the approved Azure Container Registry 'mkskytt.azurecr.io'. Only images with the prefix 'mkskytt.azurecr.io/' are allowed."
      pattern:
        spec:
          ephemeralContainers:
          - image: "mkskytt.azurecr.io/*"