---
# External DNS service to create DNS records for k8s.mkskytt.dev domains
# This points all k8s.mkskytt.dev subdomains to the cloudflared tunnel
apiVersion: v1
kind: Service
metadata:
  name: tunnel-dns-target
  namespace: default
  annotations:
    # Create DNS records for all the k8s.mkskytt.dev subdomains
    external-dns.alpha.kubernetes.io/hostname: "app.k8s.mkskytt.dev,api.k8s.mkskytt.dev,dashboard.k8s.mkskytt.dev,hubble.k8s.mkskytt.dev"
    # Set the target to your cloudflared tunnel CNAME
    external-dns.alpha.kubernetes.io/target: "your-tunnel-id.cfargotunnel.com"
spec:
  type: ExternalName
  externalName: "your-tunnel-id.cfargotunnel.com"
  ports:
  - port: 80
    name: http
  - port: 443
    name: https