apiVersion: v1
kind: Secret
metadata:
  name: motorinfo-db
  namespace: motorinfo
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: ENC[AES256_GCM,data:7/bjVkCmpEe0J6Q/Q2Xnxb71ng53lk48iN6eFVjRxecZ0NXGqQUJdH4+8j8UgZhNVZMF6pn2xziWd/amnULMfg2l1gUBszUy2POVnRhO3qo13ZhdP4cT6TRaE0dQO/QViB9q6t6He7qU9Quc7Qef5QEUWjn402U9aP3vu/PzCJnFbzk=,iv:1YOiYcSyIwpIxA/m4//x5yBZoNVSfOFRePtaYNXoTC0=,tag:PbBweXX1Qe0iqLA4FR6D2Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOdjZwd3pIMHRkajhVWkc5
        dEgyWUVhdjk3TmZsS1l3cGFNUkgzNFZMckQ0CjB3alJQSG1neDZYQi95T1pibnIr
        cjVaV1AySmFkWTVod1FsTnpVcEJLMGcKLS0tIHNERzArZXQxc21oWUVhLzkySmJV
        TVBjcXNmMm5QSG1CMjVoY2pqNHh6Y28KEqGYtx21mXC1GPpmVa0iETw8uO9hgqmS
        ZW62yQBE2hgcXPs2d/WFj2bp9d35qOEXzEapisAEzEG3sTwXz8j2Yg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rdt2uehxek8mqjec354t3k2wewmsqgksvx8runc7s6e0ljh3yavsw2vyma
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T14:07:22Z"
  mac: ENC[AES256_GCM,data:g/8xYPsolAL/OSyEZ2SNlcBur7EGNggvFBHdq6LUNhyGZSjHAXTNNDvNTabylymFpPgbUFcSZvZDzxLL+lu7ZoGGc0M03NKTXRV+9hd3/SDWwDVK8t+TC+3/aQiEuX/1D3mF6WL4TeYAfSV+lB9PVvuCun6fV/Y4zEPQHd2i4K8=,iv:d06/UYXgtyGtnol8a0bStDvpBRdj6s4mPZrr4NGgr8g=,tag:bp/n7LFE3HnSjsfnIcFv5Q==,type:str]
  version: 3.13.1
