---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: motorinfo-api
  namespace: motorinfo
  labels:
    app.kubernetes.io/name: motorinfo
    app.kubernetes.io/component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: motorinfo
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: motorinfo
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: api
          image: ghcr.io/mkskytt/motorinfo-api:1c6509c
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
          envFrom:
            - secretRef:
                name: motorinfo-db
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /health/live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: motorinfo-api
  namespace: motorinfo
spec:
  selector:
    app.kubernetes.io/name: motorinfo
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
