apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - motorinfo-db-backup-creds.sops.yaml
  - motorinfo-db-role.sops.yaml
  - motorinfo-db.sops.yaml
  - pyroscope-auth.sops.yaml
  - database.yaml
  - deployment-api.yaml
  - deployment-web.yaml
  - ingress.yaml
