apiVersion: v1
kind: Secret
metadata:
  name: motorinfo-db-role
  namespace: motorinfo
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:0bVcBnzo32We,iv:wwPVtiC7IakZhvnkkCFsCqej+aDCS7ZNuCvicFcbyeE=,tag:wMwDyUcADUMsY7e7yj/jnA==,type:str]
  password: ENC[AES256_GCM,data:zzqJhQXJB35HMnOLfPR5yA3tZfe9eHevqyOCGNkzoFk=,iv:8X0rrayNd/A+20y6tXHFRDE6yQYLI7YqYTa/nEqFiVw=,tag:NiMluo7eFYmLg/EjYT3Htg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByOTJNeUNrUWVwb3BCVmlH
        VVhTSThvZVBUWkZQZlAwSU5ZQTNKdlFiNUM0CkR1YjZrbXA4Vitrak5oMUh2Zk4v
        b09OSWIrdXRRQWxjZHZLNnp3MGdMUG8KLS0tIE9xamJxNytwY2Rtd0lGVjNkZEVD
        MVNmZEkrTzFxSDhEYm91Q3EweE8vejAKKrjl3Z1tKibp10aBk5bPQLDhDinKGeUV
        tgLBXaDRGYeLM+2YnNBEMiuDgER87OM32MIZAfLaMywP2jwEkOvzJQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rdt2uehxek8mqjec354t3k2wewmsqgksvx8runc7s6e0ljh3yavsw2vyma
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T14:54:52Z"
  mac: ENC[AES256_GCM,data:XPp3FPa/ogKxeVhm7aULhTHqzxyeBBmXiOcYjBtjnpJWI/ppIr2+zv+QCLe7GLlpNUBweJzAvS9oR3oigU4A9rLaCDKwpM16l6nDKRYRDGNw53lFfGjyL5sM1BG9TTfnk9LrcvdkVotgcInOyp4qMGyRFJKKqTbhMOSoNf7tKls=,iv:b3fjVgpkEWHPq/6v2AVz/+6whh4ZIwJ6+ifrbIDI6Ts=,tag:P7wbc28cJ8FgiMkJUX8O3g==,type:str]
  version: 3.13.1
