apiVersion: v1
kind: Secret
metadata:
  name: motorinfo-db
  namespace: motorinfo
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: ENC[AES256_GCM,data:fW4Fn2glRt2rvobzulcXwJTs2QNI/j/txejRi8zeT51fZTVjnRXmap1Sv77dyKQD46SKFsOGVmBVIyO65tpq65S2Mys+uGvmqnLjZvDM96zcsEGkTXZsPFJMrfhovSxEvggA9cwZLPCe96jXPm2Z8BQ7Dzuijfi9l+z2Ksgqdix1cU96Q3jHRrRI,iv:lBe3zZivdzNnZ9XwSMbpSJ2WriiM4tuuuCTqgBYbg2c=,tag:nd968Zz2ZLxraNULYxjsCQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZlR6UGxaNVZPNVhTRjJG
        aXYxODlUSXJIUFlOUWNWL2xMNFJiV0dReDFZClcyR3NJZGlQY1BYTGJrcVhLeW9r
        Q2xGWDZuMUMxZ05pVkZ4c21aVWZjTFEKLS0tIG0rWW1NUkhYYytaVk0wdGVJWThw
        Nk9wQUJrZWtFRFF3dllXakhqV0hRN2cKYWwHcYEJSqa+K5DFeowG/U7rnBPJGpnf
        7jMAQpa1pkw8EcyAmm2SBssPgRJYTIgkLXpugMH+vofGrJ7FPTFfag==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rdt2uehxek8mqjec354t3k2wewmsqgksvx8runc7s6e0ljh3yavsw2vyma
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T14:54:52Z"
  mac: ENC[AES256_GCM,data:Y6fAMwpDfQv978PEc0TKAHgzfYCgy7ARAmRNiLPXQiGySxrey2eQQ6ZLorNQWlFjoZljftfjtOMCUar9qTp+7pDkkzGPYRmTSAr/7HR/TI0ZJ5u6krY+VMlJoRTK1silme4KXuFk5kXH1MVkq7WXf51dHOFpRYqFfEiosTJjlj4=,iv:cPL6UN4nf1qUwh3ozRyECa45UjNT5o3Xvao20JcQnUk=,tag:0fuc/NJ7ZkXcigVRvMzA3Q==,type:str]
  version: 3.13.1
