apiVersion: v1
kind: Secret
metadata:
  name: motorinfo-db-backup-creds
  namespace: motorinfo
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:0irzLcvDKV0+cRzv3weMDgvRjqY=,iv:4whgQr3UgSkPXoKqPlw1wZFT8hX1Xyr3NPhwVf4OIrA=,tag:TIPq5FnJiA1tlFCquEXoVQ==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Iz6MD6wnxdtCNYzV7nnBLJ23cbptwC71g2pO0HqGI3sJkUeWpbD/mg==,iv:x23D5BB/pnweEHgPUTmLARxt2s3Thf9Yastda2eHTog=,tag:/6FD7pmYg8QbSLarMY/uIg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCeTNyM2pVS0FXRFVoUkxQ
        emF5WEhHRERxRm5SRVM2UHd5NzFsbWNQL1JFCld4KzdHNnNraE1RbllSVzFDWHdE
        RjJlMTN2cHdOc0VKaGU2azhOL0lBMjAKLS0tIFdoQ0dXNmZQSERwLy9CdXF3VU10
        alAxM2F5bVFuL21RbitsbDhwMEZIRFkKVc5gKqwz0ip3yk+cyc8cfUkVwsVe2w03
        pFMor0V93MKE2OtM4xTJ8CAX90f8EU1VGMI+ATqLqc+K647RHDJf8A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rdt2uehxek8mqjec354t3k2wewmsqgksvx8runc7s6e0ljh3yavsw2vyma
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T14:54:52Z"
  mac: ENC[AES256_GCM,data:McbVUPAH3Lw6YoPI/KTaOH24RI5WvmpwfwivuAGpog7rMMYpFnJ8wvIaCoaKVCbGbPixacnr+hLwNOID3AVinhZajbkdE/IVkMnWJGEHkfHPu0LLmZljhHIek/+OvfWSlenhcfz8oXJoViOgn1QXvABzjzOu1gC95zGgAlw75fs=,iv:hbrThVHC/qC3/bjrrPaqnthIZEU1zFybtfzamz5NNFQ=,tag:Ub/p2MCpZ0np+9xLyUSszQ==,type:str]
  version: 3.13.1
