apiVersion: v1
kind: Secret
metadata:
  name: pyroscope-auth
  namespace: motorinfo
type: Opaque
stringData:
  PYROSCOPE_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:UaItRalU4qYTiU8iepjWowUf8eRxZkPwLc0uQy9ypzguyW/Hx93kkYuzFUGOjZd0NqYCQVULyvhYZwQwbpURx50Hg+c7hYUtsBs28ye00SEjHvxcaFd6SEGhtO3F5+IuFS0UvflNfl/QNgfQTcZxj/wzOmlf+Uqf+aa4clWLHKg4WWJpskiSJ3zyqyPtVT/t5NGByQ==,iv:2f1eAzS3cTNCAdFdgCGoWegwqJcxM4vnDcOFaY4V8uM=,tag:sBrBr7giwwQA01SMrhGaSw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbDZaSnUvQVY3YytVeTZK
        S3R6b1NjNTNPeDc4eVJYSyt5elVwUy95MkFBCkNvU0t1ZVFMVzNWemlQSmlQREVr
        eEFwdGVxYWNRYURZSENiejVaV0oxK28KLS0tIDZWVStuZUd1eEhzMlpzRkZsTXhH
        RzJZd293Z2Z3QXlLU2RHN0Nwc0NRVlEKQYD298s8DLkdIIxEIFXFiTScJXc4pOZL
        vTCLXXV3VexmCML3nrUDjRfLBSwgTZPiYa2mUINGXcNQjOc/FGGfFQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rdt2uehxek8mqjec354t3k2wewmsqgksvx8runc7s6e0ljh3yavsw2vyma
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T20:25:03Z"
  mac: ENC[AES256_GCM,data:q/q6e2JU+gFGNqWugl7t6n9c/QXaLvZYwffpTmZrf/WlVcZPrBbqq9cAw9PD7jgr7UeYAgA1xx/lwAllueGz/cuIbvp95BZhP6+cMwb1dbV2lzfS70U4LGN6M05XAYdIEL6+InT3guZvZQ8KHYA3NX7jDakRfpzBb1cm88K+Yio=,iv:nB8ncuMW3sK3/wS0OpgQQuxse7hYISPiMLqMpMjgsic=,tag:EsCIUYYabA+kKDEpMT8uwg==,type:str]
  version: 3.13.1
