apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: grafana-alloy
type: Opaque
stringData:
  grafana-token: ENC[AES256_GCM,data:oE3tP6rmQVE8FI2gSYPlnc56e1XefCbCqcvWgiaecWr1,iv:d3pCrLK7yilPJM+6ZBR1F5QtVCqxjtaRx7hXdQCljGc=,tag:pkB7sd+E7AoEJOE4cEuOhA==,type:str]
  username: ENC[AES256_GCM,data:rw==,iv:2zNQau9EJHzGgKwLGT9MjYaEXwbFhF/bNdVKIdJc5uo=,tag:Hux7L2h6D3lfYogoRZwN4w==,type:str]
  logs-username: ENC[AES256_GCM,data:0A==,iv:ySizpB+7J6hPvZbifcemy6tB7hslFzZWW0dTUAB7vC8=,tag:EtiyXNefAcUXLMpsxXuNRg==,type:str]
  otlp-username: ENC[AES256_GCM,data:Wg==,iv:1qNckOvEGBQmBTNYdlzDDIOoNHLpQCuixx6bnvmggp0=,tag:Qev6zBS0pjhiuqkxY9m8fw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZnFGM05oWGZuUjFNcCsz
        MWNTcjZmdXBxNjJaU2l3STFOZUJoS3NaMjNnCm04U0JqS2xURU1KNjUzdEZyZ1A4
        QjlZcGUwd2xsVkRRckJkbktFQlRpdDgKLS0tIHVhYURLSnpQTnp2RFBjY0FDb2dn
        aldWT3JoNXJEdnQ4eFlZcGdDaG90ZmsKK2ahp5epJpAT8TputQMXykfdVynCpV4P
        qCi/PcSPITGIA4OHWlZSzjIspVEBF13AI2MonpR75hMur27Jbl5vxQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rdt2uehxek8mqjec354t3k2wewmsqgksvx8runc7s6e0ljh3yavsw2vyma
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T08:42:22Z"
  mac: ENC[AES256_GCM,data:XD0DBc5d9Hyh/zkaDW0m4RC7Bk9SQbXmeeBpVEngfTHm3HuX3HM3VA/QhzL9OyvrLau49XxZgjcleiRI15ixbfTxuJZIhHFGrk96itDh6blTSyEeF8XOsNxkE2jXRuTDgivDS2dSRVeiQDyQAXbJHl5kl9BMYFiuBrw7J+h4wv0=,iv:pCH59d2w0TOlsUz6cKaB2xfLeMuOOcjNS3x1TgjnivQ=,tag:GNCRXB/bB+s1cVv2pyN2kQ==,type:str]
  version: 3.13.1
