apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials
    namespace: grafana-alloy
type: Opaque
stringData:
    grafana-token: ENC[AES256_GCM,data:A48njmVdFBvCTO1nnOl4LQPyGLI83WDPtfxozYrKB6aOPpbnxK0Qy+Ee+Y9kg9ODp/ZFJoBzrxHUKx2FgI9mJWV1n2h5vImXm/3v/gOOwR++Yyp6ZCSe5aPsIR7T98mPaUq7WSVwbC1mXJPft1mefAstE4NGogNYyZAu7VLPU9KmbQHobdryc0traLEydWm6d+xnqzsdeU6xKYsO,iv:Kx5NJYn9rG3AJgSgXDXUTeW9nGQzOQRQ4GlE20QgGDg=,tag:GQkISzVDXNrAd/2G9KeQEw==,type:str]
sops:
    age:
        - recipient: age1zryf0de4nada4xh4fumdfrzuynd4djgj9qhx8es2kxczg6lar58q37stuk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQODFWOWI4VmovTEJ6dHV1
            V2pVcWRsUDVZaHRuUUltd2cwY1BaZzBDMGd3CkFkOVpKZ1JtZ2pXaUxZZDFSZXN6
            Q2IreUVWaG52N1BXcDdhcFM2QVZPdjgKLS0tIDB5K1JZS1FLbDVxQTczVTBGOTFX
            K3VxVnM0OHgva2hZRjZxVjVvVDFZbDAKS/104GpyN7ds+DkWo0etbE4D6VroAGKY
            iaz8lS5VlSvB+WTXnXUpM4PPry8OWZxDvDhH+5n22zlk267Un0A+FQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-28T21:35:09Z"
    mac: ENC[AES256_GCM,data:vQV86t8sMmuyx8iYvxPYdhkiYOjpVCbc720rP7Xxz5P9pW75Oo7OO8+DvrOmS1Yg7MO/ReQcw29Tv+VGJ8Qti1irmhN8aZ6U9N5xrwKlRYgn979sxE1ejlZtS4O8qA3sFEsLpxj8b0aa4Td0JmKjqmo9L2HCm2p/U838LyfxQDk=,iv:OdivoYtfzLKaOaZpKqNSJ8RXkzkbEg3BBOUFBZt3ukI=,tag:7ae/ACULwhP0LZfnSHRCpw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
