apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: grafana-alloy
type: Opaque
stringData:
  grafana-token: ENC[AES256_GCM,data:SfAf+zb/GW5Bw262F95yAQHU8zV9YqBgBpY1UUbPtIXR7tjev8dotHf6JZ/91WhgNBx0fbppG4KBvhZPUdd0qNH1ufEs5rEUI3IO6fRi32Vkd7pgO6mwgwGkIlHDez9n9H5tcSDELbkH3ODrNIPkhR7WRuDiRQyFad7V823EYNsVDPUn+JO2/ybZYdQ=,iv:Moc8n1agqLdAqMNoZ4kqkjkFUmtOeSEEWuVBAtWiiK8=,tag:y8E7bhetQF5yvFGUGjRehw==,type:str]
  username: ENC[AES256_GCM,data:9qmngoj9Rg==,iv:9koNpnvPmBhslj5FKS2m86P/bPkguZimgDnLDC8FNyg=,tag:GWoarjTpqbsd14jW8RlwoA==,type:str]
  logs-username: ENC[AES256_GCM,data:mjtmp2FhMQ==,iv:g80AcYFJNRFXSDQd/mXzGCATPjbyk9GCZ95i2nAA9k8=,tag:mYAUqrrSsdmVf0dstRMcZg==,type:str]
  otlp-username: ENC[AES256_GCM,data:Kk0+W4jr,iv:N/Lceb+2eJmck4onSG8I8QFhuUCBfPGiVU2bRIK5oE4=,tag:mAR3IiOJrcmfipdaqUjuEA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMGdGU091YXVKUDBFdlk3
        UWZheloyZEcrNFQzQWVrODlVaVM2OHpMWkNRClh1OU5XaXVvaGdORDBTeHRDQ1hH
        Umx0MmJXN1VTY0kxTlNCSHZmTVpZbjQKLS0tIFB1K1k3QkFvWk9nOE00aXVuanMr
        ZmlrOXdvWjZLZkFKQkhPNEoxVnhGL3cKuiGcs8vX4qIu5pSemODGn5+YloDSP8gM
        GoGuSM2pCRHcrzMXtmba3b3zBqxe8aYmWF3XluAnDQjchTy2pYwcMw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rdt2uehxek8mqjec354t3k2wewmsqgksvx8runc7s6e0ljh3yavsw2vyma
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T09:09:33Z"
  mac: ENC[AES256_GCM,data:7uL3wp2fcfrhOAFJjBr6QY1RiHvAv4f4mr0QNrMEaec/aKiLBh2PiNP5nwRk3OkkxyiWnRvGgGF394DZb9M7wxcDnY4sIJLiTXhjAAUnQyrTHS81DVswF9zF0kItYdEcJYF29bxU14K4pw+G72MuBCz3HB57Ic2KDcqpU3P/kFo=,iv:g1MrWkfwo3Jyup+08LkdFcDYKH67LZmIzxApZIqOfQE=,tag:VQsEmKWA9zpaC/JENrkS7A==,type:str]
  version: 3.13.1
