---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: grafana-alloy
spec:
  url: https://grafana.github.io/helm-charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-k8s-monitoring
  namespace: grafana-alloy
spec:
  interval: 30m
  chart:
    spec:
      chart: k8s-monitoring
      version: ">=1.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana-alloy
      interval: 12h
  values:
    cluster:
      name: k8s-cluster

    destinations:
      - name: grafana-cloud-metrics
        type: prometheus
        url: https://prometheus-prod-22-prod-eu-west-3.grafana.net/api/prom/push
        auth:
          type: basic
          usernameKey: username
          passwordKey: grafana-token
        secret:
          create: false
          name: grafana-credentials
          namespace: grafana-alloy

      - name: grafana-cloud-logs
        type: loki
        url: https://logs-prod-013.grafana.net/loki/api/v1/push
        auth:
          type: basic
          usernameKey: logs-username
          passwordKey: grafana-token
        secret:
          create: false
          name: grafana-credentials
          namespace: grafana-alloy

      - name: grafana-cloud-otlp-endpoint
        type: otlp
        url: https://otlp-gateway-prod-eu-west-3.grafana.net/otlp
        protocol: http
        auth:
          type: basic
          usernameKey: otlp-username
          passwordKey: grafana-token
        secret:
          create: false
          name: grafana-credentials
          namespace: grafana-alloy
        metrics:
          enabled: true
        logs:
          enabled: true
        traces:
          enabled: true

    clusterMetrics:
      enabled: true
      kube-state-metrics:
        podAnnotations:
          kubernetes.azure.com/set-kube-service-host-fqdn: "true"
      opencost:
        enabled: true
        metricsSource: grafana-cloud-metrics
        opencost:
          exporter:
            defaultClusterId: k8s-cluster
          prometheus:
            existingSecretName: grafana-credentials
            password_key: grafana-token
            external:
              url: https://prometheus-prod-22-prod-eu-west-3.grafana.net/api/prom
      kepler:
        enabled: true

    clusterEvents:
      enabled: true

    podLogs:
      enabled: true

    applicationObservability:
      enabled: true
      receivers:
        otlp:
          grpc:
            enabled: true
            port: 4317
          http:
            enabled: true
            port: 4318
        zipkin:
          enabled: true
          port: 9411

    alloy-metrics:
      enabled: true
      controller:
        podAnnotations:
          kubernetes.azure.com/set-kube-service-host-fqdn: "true"

    alloy-singleton:
      enabled: true
      controller:
        podAnnotations:
          kubernetes.azure.com/set-kube-service-host-fqdn: "true"

    alloy-logs:
      enabled: true
      controller:
        podAnnotations:
          kubernetes.azure.com/set-kube-service-host-fqdn: "true"

    alloy-receiver:
      enabled: true
      controller:
        podAnnotations:
          kubernetes.azure.com/set-kube-service-host-fqdn: "true"
      alloy:
        extraPorts:
          - name: otlp-grpc
            port: 4317
            targetPort: 4317
            protocol: TCP
          - name: otlp-http
            port: 4318
            targetPort: 4318
            protocol: TCP
          - name: zipkin
            port: 9411
            targetPort: 9411
            protocol: TCP
