apiVersion: v1
kind: Secret
metadata:
  name: pg-demo-backup-creds
  namespace: pg-demo
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:xIkyy8Bhgdch9OgJk6P4wzTJbGI=,iv:5GE0LM4/khVysbQcEAYsvU1AnT9f+iVgIKYz/Ej5fqg=,tag:yBToaGBNtXW21EapNe7E/Q==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1rXCvVT+sJrAouKBYaYibAdTaSv+dSpqIoVW/SYh+xh4NS/l1H2uhw==,iv:g9tPBhFWcZD8RJvIvIvT5VB5pjyCX4URY7ALJn2Wths=,tag:hgPkxs2oDpGV/54SBxOW2Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrZE9jK3VhM2FCNFNmUHBx
        YzFyaHBlZEZ3NWN5dzljYXI5ckdhd0N4VWpBCnI2aEpzYWlrSlVFMGtpcEZ2VVdN
        RVVTVWdTZEpSdy9LZ0FTbDZnRkd0MUEKLS0tIHBVWURRZy93UXB2NWZmRmlhbU0z
        ck5hbE9BeFhOSTRvaVpkbzZTb29HRGMKV2PNpnpfRPGA8Ew8bptyKcQsFODznZ7O
        lnebubNIZDSk2wZOYr3Lhg/K2LQA1DBpOEgQhck5SJYqMG5Oc4DG2w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rdt2uehxek8mqjec354t3k2wewmsqgksvx8runc7s6e0ljh3yavsw2vyma
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T13:14:03Z"
  mac: ENC[AES256_GCM,data:vsIUE44jH68ispPLjLL7hz6XIDT7mgTcSw5R0PMgam6g/R4OrsMj6g9OzboJeUiV9KqGltobars9cYyukRUG/Xnsd7EFWE3VefmvwZ2od9YFNzX0JFRxjMj6tH+b4/C7Q3wfcCFdGlyYspCpeJ9Wd/xMRTjEEKVLEiA7aiVmj7o=,iv:YNRdLDAeiqqrVYxrWEjdA3SFVOuz9wtqJ9Kh4NIbgwM=,tag:YXtj/ON0ahXrMHrsIKb+jg==,type:str]
  version: 3.13.1
