apiVersion: v1
kind: Secret
metadata:
  name: motorinfo-db-credentials
  namespace: pg-demo
type: kubernetes.io/basic-auth
stringData:
  username: ENC[AES256_GCM,data:dpOVIMUSoca7,iv:akza/rMeaLLBSZGBgiJEaBu+em+VRItsV1N/QFIcnrM=,tag:FTmeQuPpsWkdH6ZQxcSl8A==,type:str]
  password: ENC[AES256_GCM,data:B279yI0loS7EgxykYj4V83Q67rtqkvG5p9KkH7GXlvQ=,iv:H1DUCmVM/iHN0KLtRdZkKn2h9GUwINMdiIq5LZLXci4=,tag:YzGEMPz7Gv6Ch9SptL0S+A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUVVncmFQYlV0TzJlaExx
        VERRWFcwWU5oWEhZTWN1KzVxbFhQeTc5MDJFCkRvWTJ0clRaVWpjZ1doT1NFSVcz
        aG1vMGdNMHZOaW9PckN5MVN2bjBVWGMKLS0tIHZaQUlLZGF5YWFobG9hSHlOTE44
        TVJuVlJZZHRQQmRsK3hTZFY1dEJYekkKYQADa4Rg5YrDjYBYkJm2ZK1YncwNY6Sc
        QjUSIfJVIhKs1fnOZ895UU3+5wL/jx2ylhZlFd59Q0e/7yhYsVSITg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1rdt2uehxek8mqjec354t3k2wewmsqgksvx8runc7s6e0ljh3yavsw2vyma
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-21T14:07:22Z"
  mac: ENC[AES256_GCM,data:sQpFlqnTnuMtqSva5PnoanRG2foAh/FXMauTepiA1Ke8p7/2KEJz8lLPCjXeLYEN8uMeyrl6/oP8wB66zlVLao/A9296BG4L8qAKKXAScV1Ms1Sml2GjMfcNfLtPKD7VqT4gRLSSAfXdJP3DVLn1xaujoKphC7UpQNyUU4lHPtQ=,iv:YDp11P7F5uHzAY8hJC7oKT8gu7rxxkot8gLbOcTqgDw=,tag:mFNdDsXd6VKFQs/kmvZTiQ==,type:str]
  version: 3.13.1
